# Site settings
title: Yet another blog about getting rich (while doing GSoC 2015)
description: I participate at Google Summer of Code 2015. AWESOME! Students are encouraged to report progress in a blog. And now guess where you are.
baseurl: "/gsoc15" # the subpath of your site, e.g. /blog/
url: "http://mar-v-in.github.io" # the base hostname & protocol for your site
social: 
   github: mar-v-in
   email: gsoc15@larma.de
paginate: 5

# Build settings
markdown: kramdown
