# Site settings
title: GSoC 2015 - Yet another blog about getting rich
email: gsoc15@larma.de
description: I participate at Google Summer of Code 2015. AWESOME! Students are encouraged to report progress in a blog. And now guess where you are now
baseurl: "/gsoc15" # the subpath of your site, e.g. /blog/
url: "http://mar-v-in.github.io/gsoc15" # the base hostname & protocol for your site
github_username:  mar-v-in

# Build settings
markdown: kramdown
