# Site settings
title: GSoC 2015
email: gsoc15@larma.de
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/gsoc15" # the subpath of your site, e.g. /blog/
url: "http://mar-v-in.github.io/gsoc15" # the base hostname & protocol for your site
#twitter_username: 
github_username:  mar-v-in

# Build settings
markdown: kramdown
